version: '3'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=mongodb://mongo:27017/myapp
      - REDIS_HOST=redis
      - REDIS_PORT = 6379
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379
    restart: always
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  mongo-data:
  redis-data:
